name: Artifact Challenge
env: 
  ARTIFACT_NAME: 'challenge-artifact'
  
on: [push]

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: name
        path: .${{ env.ARTIFACT_NAME }}
