name: Custom Action

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Run custom action
      uses: "jackjduggan/learning-github-actions-custom-action@main"

    #- name: Make script executable
    #  run: chmod +x /usr/local/bin/script.sh

    - name: Run script
      run: sh /usr/local/bin/script.sh
