# 4 jobs
# each prints the date
# job 1 = ubuntu-latest
# job 2 = windows-latest
# job 3 = macos-latest
# job 4 = ubuntu-latest, dependency on the jobs 1,2,3
name: date-challenge

# trigger
on: [push]

jobs:
    ubuntu:
        name: Print Date Ubuntu
        runs-on: ubuntu-latest
        steps:
        - name: Print the date
          run: date
    windows:
        name: Print Date Windows
        runs-on: windows-latest
        steps:
        - name: Print the date
          run: date
    macos:
        name: Print Date MacOS
        runs-on: macos-latest
        steps:
        - name: Print the date
          run: date
    depends:
        needs: [ubuntu, windows, macos]
        name: Print Date Bonus
        runs-on: ubuntu-latest
        steps:
        - name: Print the date
          run: date